version: 2
checks:
  method-lines:
    config:
      threshold: 60
plugins:
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - HACK
        - XXX
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
exclude_patterns:
  - grifts/**/*
  - "**/*_test.go"
  - "*_test.go"
  - "**_test.go"
  - logs/*
  - public/*
  - templates/*

# see https://docs.codeclimate.com/docs/advanced-configuration
