language: go

go:
  - "1.11.x"

env:
  - GO_ENV=test


before_install:
  - mkdir -p crdb/certs
  - pushd crdb
  - wget -qO- https://binaries.cockroachdb.com/cockroach-v2.1.0.linux-amd64.tgz | tar  zxv
  - mv cockroach-v2.1.0.linux-amd64/cockroach .
  - rmdir cockroach-v2.1.0.linux-amd64
  - ./cockroach start --insecure --background
  - popd

before_script:
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets

go_import_path: github.com/hyeoncheon/skel

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - go get github.com/gobuffalo/suite
  - go get $(go list ./... | grep -v /vendor/)

script:
  - rm database.yml
  - cp database.yml.travis database.yml
  - buffalo test
