language: go

go:
	- "1.11.x"

env:
	- GO_ENV=test



before_script:
	- mkdir -p $TRAVIS_BUILD_DIR/public/assets

go_import_path: github.com/hyeoncheon/skel

install:
	- go get github.com/gobuffalo/buffalo/buffalo
	- go get $(go list ./... | grep -v /vendor/)

script: buffalo test
