language: go
dist: bionic

go:
  - 1.17.x
  - 1.18.x

env:
  - GO_ENV=test
  # set CC_TEST_REPORTER_ID here or settings of Travis-CI.


before_install:
  - nvm --version
  - nvm install lts/fermium
  - node --version
  - env
  # cockroachdb
  - mkdir -p crdb/certs
  - pushd crdb
  - wget -qO- https://binaries.cockroachdb.com/cockroach-v2.1.0.linux-amd64.tgz | tar  zxv
  - mv cockroach-v2.1.0.linux-amd64/cockroach .
  - rmdir cockroach-v2.1.0.linux-amd64
  - ./cockroach start --insecure --background
  - popd
  # buffalo
  - go install github.com/gobuffalo/cli/cmd/buffalo@latest
  - buffalo version
  - buffalo help
  # goveralls
  #- go install github.com/mattn/goveralls@latest

install:
  - go mod tidy
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets
  - touch $TRAVIS_BUILD_DIR/public/assets/empty
  - yarn

before_script:
  # for codeclimate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

go_import_path: github.com/hyeoncheon/skel

script:
  - rm database.yml && cp database.yml.travis database.yml
  - buffalo test -coverprofile c.out -covermode=count ./...

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
